### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by cristiansteib**
Compatible with python3,
Update the readme, missing instructions to install.

### CODE REVIEW

**Comment by Macleykun** [comment]
Any eta when this can be merged @Jacksgong ?

**Comment by Macleykun** [comment]
@cristiansteib @Jacksgong i'm working on automating this in Github Workflow.
Is either one of you still active on this platform to accept this pull?

**Comment by Jacksgong** [comment]
thanks so much for your pr, but there are some issues on this pr, python3 has been adapted on v4.1.0.

**Comment by Macleykun** [comment]
so, is python 3 gonna be pushed to the upstream?
are you available for this extra feature to run this in github workflow/actions?

**Pull request closed without merging**
